version: '3.4'

services:
  TrafficInfoApi_1:
    image: trafficinfoapi
    container_name: trafficinfoapi_1
    build:
      context: ./
      dockerfile: ./HostedServices/TrafficInfoApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8880:80"
  