version: '3.4'

services:
  TrafficInfoApi_1:
    image: trafficinfoapi
    container_name: trafficinfoapi_1
    build:
      context: ./
      dockerfile: ./HostedServices/TrafficInfoApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8880:80"
  
#USA
  Airport_new_york:
    image: airport
    container_name: airport_new_york
    build:
      context: ./
      dockerfile: ./HostedServices/AirportService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8801:80"
    command: --name="New York" --color=#0000FF --latitude=40.68 --longitude=-74.17
  Airport_miami:
    image: airport
    container_name: airport_miami
    build:
      context: ./
      dockerfile: ./HostedServices/AirportService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8802:80"
    command: --name="Miami" --color=#0b40f4 --latitude=25.78 --longitude=-80.17
